### ISSUE TITLE
Problem with urls

### ISSUE THREAD

**Issue by mlliarm** [mlliarm/protoselida#2]
After changing the encoding to utf, we get urls as the following:

`https://www.frontpages.gr/d/20190628/b'1/\xce\x97-\xce\x9a\xce\xb1\xce\xb8\xce\xb7\xce\xbc\xce\xb5\xcf\x81\xce\xb9\xce\xbd\xce\xae'.jpg`

It should be instead:
`https://www.frontpages.gr/d/20190628/1/Η-Καθημερινή`

**Comment by mlliarm** [comment]
Changed back to the original version of the code.

Not sure why urrlib fails to download the images.

```
https://www.frontpages.gr/data/2019/20190628/HKathimeriniI.jpg
ERROR 404: Paper HKathimeriniI not found !
 
https://www.frontpages.gr/data/2019/20190628/TaNeaI.jpg
ERROR 404: Paper TaNeaI not found !
 
https://www.frontpages.gr/data/2019/20190628/EthnosI.jpg
ERROR 404: Paper EthnosI not found !
 
https://www.frontpages.gr/data/2019/20190628/EfSynI.jpg
ERROR 404: Paper EfSynI not found !
 
https://www.frontpages.gr/data/2019/20190628/EstiaI.jpg
ERROR 404: Paper EstiaI not found !
 
https://www.frontpages.gr/data/2019/20190628/AugiI.jpg
ERROR 404: Paper AugiI not found !
 
https://www.frontpages.gr/data/2019/20190628/EleutherosTyposI.jpg
ERROR 404: Paper EleutherosTyposI not found !
```

**Comment by mlliarm** [comment]
```
>>> url = 'https://www.frontpages.gr/data/2019/20190628/TaNeaI.jpg'
>>> urllib.request.urlopen(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by mlliarm** [comment]
https://stackoverflow.com/questions/16627227/http-error-403-in-python-3-web-scraping
https://stackoverflow.com/questions/18491416/pil-convert-bytearray-to-image
https://stackoverflow.com/questions/41850407/image-from-bytes-python?noredirect=1&lq=1
